version: "3.3" # Mostly as I don't use compose >3.8

services:
  mongodb:
    image: mongo:4.4.18 # Mostly as I can't support >5
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db # mostly as I wanted to keep relative data nearby

  express:
    build: ./server
    container_name: express
    command: npm start
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employees
    ports:
      - 5000:5000
    volumes:
      - ./server/:/app/server # this
    depends_on:
      - mongodb
      
#    network_mode: host

  react:
    build: ./client
    container_name: react-frontend
    command: npm start
    ports:
      - 3000:3000
    environment:
      - API_URL=http://express:5000 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/:/app/client # this
      - ./client/:/app/client/node_modules # this
    depends_on:
      - express
