version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    # volumes:
      # - mongodb_data:/data/db
    network_mode: host

  express:
    build: ./server
    container_name: express
    command: npm start
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employees
    ports:
      - 3000:3000
    # env_file:
      # - ./.env.dev
    volumes:
      - ./server/:/srv/app
    network_mode: host

  react:
    build: ./client
    container_name: react-frontend
    command: npm start
    ports:
      - 5000:5000
    # env_file:
    #   - ./.env.dev
    network_mode: host
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/:/srv/app
      - /srv/app/node_modules
    depends_on:
      - express

