version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  express:
    build: ./server
    container_name: express
    command: npm start
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employees
    ports:
      - 5000:5000
    volumes:
      - ./server/:/srv/app
    depends_on:
      - mongodb
      
    network_mode: host

  react:
    build: ./client
    container_name: react-frontend
    command: npm start
    ports:
      - 3000:3000
    environment:
      - API_URL=http://express:5000 
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./client/:/srv/app
      - ./client/:/srv/app/node_modules
    depends_on:
      - express
volumes:
  mongodb_data:
