version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  express:
    build: ./server
    container_name: express
    command: npm start
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employees
    ports:
      - 5000:5000
    volumes:
      - ./server/:/srv/app
    # network_mode: host

  react:
    build: ./client
    container_name: react-frontend
    command: npm start
    ports:
      - 3000:3000
    # env_file:
    #   - ./.env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_URL=http://0.0.0.0:5000 
    volumes:
      - ./client/:/srv/app
      - /srv/app/node_modules
    depends_on:
      - express

    # network_mode: host
